<?php
use Drupal\Core\Url;
use Drupal\Core\Link;
/**
 * @file
 * Contains contact_crud.module.
 */

/**
   * {@inheritdoc}
   * Get Pager
   */
  function getPager(){
    $query = \Drupal::database()->select('contactcrud', 't');
    $query->addExpression('COUNT(*)');
    $count = $query->execute()->fetchField();


   $count = ceil($count/15);

  $page_link = Url::fromUserInput('/ajax/contact_crud/table/page/0');
  $page_link = Link::fromTextAndUrl('<<', $page_link);
  $page_link = $page_link->toRenderable();
  $page_link['#attributes'] = ['class'=>['use-ajax']];
  $out= \Drupal::service('renderer')->render($page_link);
   for($i = 0; $i < $count; $i++){
    $page = Url::fromUserInput('/ajax/contact_crud/table/page/'.$i);
    $pageLink =  Link::fromTextAndUrl($i, $page);
    $pageLink = $pageLink->toRenderable();
    $pageLink['#attributes'] = ['class'=>['use-ajax','pagination-link']];
    $out = \Drupal::service('renderer')->render($pageLink);
   }
   $last_page = $count-1;
   $page_link_last = Url::fromUserInput('/ajax/contact_crud/table/page/'.$last_page);
   $page_link_last = Link::fromTextAndUrl('>>', $page_link_last);
   $page_link_last = $page_link_last->toRenderable();
   $page_link_last['#attributes'] = ['class'=>['use-ajax']];
   $out = \Drupal::service('renderer')->render($page_link_last);
   return $out;

 }
 function get_contact_form() {

   $render_array = \Drupal::formBuilder()->getForm('Drupal\contact_crud\Form\ContactForm');

   return $render_array;
 }

 function contact_crud_element_info_alter(array &$types) {

   if (isset($types['table'])) {
     $types['table']['#attached']['library'][] = 'contact_crud/contact_crud';
   }
 }

